@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package xenoscape.worldsretold.defaultmod.basic;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;